version: "3.5"

services:

  # Apache Spark

  hossein-spark-master:
    image: gettyimages/spark:2.3.0-hadoop-2.8
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    container_name: hossein-spark-master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_PUBLIC_DNS: localhost
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
      - 4040
      - 8080
    links:
      - hossein-namenode:namenode
    networks:
      - hossein-flink-spark
    volumes:
      - ./conf/master:/conf
      - /data:/data:ro


  hossein-spark-worker:
    image: gettyimages/spark:2.3.0-hadoop-2.8
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    container_name: hossein-spark-worker
    hostname: worker
    environment:
      SPARK_MASTER: spark://master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    links:
      - hossein-spark-master:master
      - hossein-namenode:namenode
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
      - 8081
    networks:
      - hossein-flink-spark
    volumes:
      - ./conf/master:/conf
      - /data:/data:ro

  # Apache Flink

  hossein-flink-jobmanager:
    image: flink:1.6.2-hadoop28
    container_name: hossein-flink-jobmanager
    expose:
      - "6123"
      - "8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    links:
      - hossein-namenode:namenode
    networks:
      - hossein-flink-spark

  hossein-flink-taskmanager:
    image: flink:1.6.2-hadoop28
    container_name: hossein-flink-taskmanager
    expose:
      - "6121"
      - "6122"
    depends_on:
      - hossein-flink-jobmanager
    command: taskmanager
    links:
      - hossein-flink-jobmanager:jobmanager
      - hossein-namenode:namenode
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - hossein-flink-spark


  # HDFS

  hossein-namenode:
    image: bde2020/hadoop-namenode:1.2.1-hadoop2.8-java8
    container_name: hossein-namenode
    volumes:
      - ./hadoop_namenode:/hadoop/dfs/name
      - /data:/data:ro

    environment:
      - CLUSTER_NAME=db
    env_file:
      - ./hadoop.env
    networks:
      - hossein-flink-spark

  hossein-resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.2.1-hadoop2.8-java8
    container_name: hossein-resourcemanager
    restart: always
    depends_on:
      - hossein-namenode
      - hossein-datanode
    links:
      - hossein-namenode:namenode
      - hossein-datanode:datanode
    env_file:
      - ./hadoop.env
    networks:
      - hossein-flink-spark

  hossein-historyserver:
    image: bde2020/hadoop-historyserver:1.2.1-hadoop2.8-java8
    container_name: hossein-historyserver
    restart: always
    depends_on:
      - hossein-namenode
      - hossein-datanode
    links:
      - hossein-namenode:namenode
      - hossein-datanode:datanode
    volumes:
      - ./hadoop_historyserver:/hadoop/yarn/timeline
      - /data:/data:ro
    env_file:
      - ./hadoop.env
    networks:
      - hossein-flink-spark
        
        
  hossein-nodemanager:
    image: bde2020/hadoop-nodemanager:1.2.1-hadoop2.8-java8
    container_name: hossein-nodemanager
    depends_on:
      - hossein-namenode
      - hossein-datanode
    env_file:
      - ./hadoop.env
    networks:
      - hossein-flink-spark

  hossein-datanode:
    image: bde2020/hadoop-datanode:1.2.1-hadoop2.8-java8
    container_name: hossein-datanode
    depends_on:
      - hossein-namenode
    links:
      - hossein-namenode:namenode
    volumes:
      - ./hadoop_datanode:/hadoop/dfs/data
      - /data:/data:ro
    env_file:
      - ./hadoop.env
    networks:
      - hossein-flink-spark
  
networks:
  hossein-flink-spark:
    driver: bridge
